name: Python CI

on:
  push:
    branches: [main]

  pull_request:

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test job
        run: echo "Running tests"

  check-python:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Check Python
        run: python --version